<?php

declare(strict_types=1);

namespace Cinece\MauticApiAuth0Bundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Auth0\SDK\Configuration\SdkConfiguration;
use Auth0\SDK\Token;



class Configuration implements ConfigurationInterface
{
    /**
     * {@inheritdoc}
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('mautic_api_auth0');        
        $rootNode
            ->children()
            ->arrayNode('sdk')
            ->children()
                ->scalarNode('strategy')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->end()
                ->scalarNode('domain')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->end()
                ->scalarNode('custom_domain')
                    ->defaultNull()
                    ->end()
                ->scalarNode('client_id')
                    ->isRequired()
                        ->cannotBeEmpty()
                        ->end()
                ->scalarNode('redirect_uri')
                    ->defaultNull()
                    ->end()
                ->scalarNode('client_secret')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->end()
                ->variableNode('audience')->end()
                ->arrayNode('organizations')
                    ->scalarPrototype()
                        ->end()
                    ->end()
                ->arrayNode('scopes')
                    ->scalarPrototype()
                        ->end()
                    ->end()
                ->scalarNode('token_algorithm')
                    ->defaultValue(Token::ALGO_RS256)
                    ->end()
                ->scalarNode('token_jwks_uri')
                    ->defaultNull()
                    ->end()
                ->scalarNode('token_max_age')
                    ->defaultNull()
                    ->end()
                ->integerNode('token_leeway')
                    ->defaultValue(60)
                    ->end()
                ->scalarNode('token_cache')
                    ->defaultNull()
                    ->end()
                ->integerNode('token_cache_ttl')
                    ->defaultValue(60)
                    ->end()
                ->scalarNode('http_client')
                    ->defaultNull()
                    ->end()
                ->integerNode('http_max_retries')
                    ->defaultValue(3)
                    ->end()
                ->scalarNode('http_request_factory')
                    ->defaultNull()
                    ->end()
                ->scalarNode('http_response_factory')
                    ->defaultNull()
                    ->end()
                ->scalarNode('http_stream_factory')
                    ->defaultNull()
                    ->end()
                ->booleanNode('http_telemetry')
                    ->defaultTrue()
                    ->end()
                ->scalarNode('session_storage')
                    ->defaultNull()
                    ->end()
                ->scalarNode('session_storage_id')
                    ->defaultValue('auth0_session')
                    ->end()
                ->scalarNode('cookie_secret')
                    ->defaultNull()                    
                    ->end()
                ->scalarNode('cookie_domain')
                    ->defaultNull()
                    ->end()
                ->integerNode('cookie_expires')
                    ->defaultValue(0)
                    ->end()
                ->scalarNode('cookie_path')
                    ->defaultValue('/')
                    ->end()
                ->scalarNode('cookie_same_site')
                    ->defaultValue('lax')
                    ->end()
                ->booleanNode('cookie_secure')
                    ->defaultFalse()
                    ->end()
                ->scalarNode('transient_storage')
                    ->defaultNull()
                    ->end()
                ->scalarNode('transient_storage_id')
                    ->defaultValue('auth0_transient')
                    ->end()
                ->scalarNode('management_token')
                    ->defaultNull()
                    ->end()
                ->scalarNode('management_token_cache')
                    ->defaultNull()
                    ->end()
                ->scalarNode('event_listener_provider')
                    ->defaultNull()
                    ->end()
                ->scalarNode('backchannel_logout_cache')
                    ->defaultNull()
                    ->end()
                ->integerNode('backchannel_logout_expires')
                    ->defaultValue(2592000)
                    ->end()
            ->end()
        ->end() // sdk
        ->arrayNode('authenticator')
            ->children()
                ->scalarNode('user_provider')
                    ->defaultNull()
                    ->end()
                ->arrayNode('routes')
                    ->children()
                        ->scalarNode('callback')
                            ->defaultNull()
                            ->end()
                        ->scalarNode('success')
                            ->defaultNull()
                            ->end()
                        ->scalarNode('failure')
                            ->defaultNull()
                            ->end()
                        ->scalarNode('logout')
                            ->defaultNull()
                            ->end()
                        ->scalarNode('login')
                            ->defaultNull()
                            ->end()
                    ->end()
            ->end()
        ->end() // authenticator
    ->end(); // rootNode

        
        return $treeBuilder;
    }

}